#!/bin/bash
yeoman modernizr
yeoman js
yeoman build
FILES="dist/.sass-cache
dist/styles/*.scss
dist/styles/*.sass
dist/*.dev*
dist/*/*.dev*
dist/*/*/*.dev*
dist/*/*/*/*.dev*
dist/components
dist/*~
dist/dist"
for f in $FILES
do
	if [ -e $f ]; then
    	echo "Cleaning up $f"
		rm -r $f 
	fi
done

zip -r dist dist
