#!/bin/bash
E_BADARGS=65

if [ -z "$1" ]
	then
  		echo "Usage: `basename $0` /path/to/folder/to/create <optional: package name> <optional: author>"
  	exit $E_BADARGS  # No arg? Bail out.
fi
echo "Creating folder $1"
mkdir -p $1 && cd $1
yeoman init quickstart

echo "Updating repository gitignore and setting up .gitignore"
cd ~/Dropbox/repositories/gitignore && git pull && cd -
cat ~/Dropbox/repositories/gitignore/Global/Linux.gitignore ~/Dropbox/repositories/gitignore/Global/OSX.gitignore ~/Dropbox/repositories/gitignore/Global/SASS.gitignore ~/Dropbox/repositories/gitignore/Global/Windows.gitignore ~/Dropbox/repositories/gitignore/Node.gitignore ~/Dropbox/repositories/bash-script/Yeoman.gitignore > .gitignore

if [ -z "$2"]; then
	PACKAGE=${1//'/'/""}
fi

touch README.md

mk-package-json $PACKAGE $3

echo "Installing common grunt plugins"
npm install grunt-beautify --save-dev
npm install grunt-modernizr --save-dev
npm install grunt-shell --save-dev

echo "Changing around Modernizr and jQuery (moving, etc), as well as installing selectivizr"
yeoman install jquery
yeoman install modernizr
yeoman install selectivizr

echo "Removing the current jQuery/Modernizr and copying the dev version of modernizr and the min version of jquery to app/vendor/js"
rm -r app/scripts/vendor

echo "Bringing in normalize.css as _normalize.scss"
mkdir -p app/styles
normalize app/styles

mkdir -p app/vendor/js
cp components/modernizr/modernizr.js app/vendor/js/modernizr.dev.js
cp components/jquery/jquery.min.js app/vendor/js/jquery.min.js
echo "Minifying Selectivizr from components to app/vendor/js"
uglifyjs -o app/vendor/js/selectivizr.min.js components/selectivizr/selectivizr.js

mkdir assets && cp ~/Dropbox/repositories/bash-script/GRUNTFILE-CHANGES assets/GRUNTFILE-CHANGES

#Finally, initialize git. This is the last task to avoid some of the stuff needing to be re-committed
git init
#git add .
#git commit -m "Initial commit"
echo "Now the basics are done! Remember to update the index.html and 404.html files to reflect the move of libraries from scripts/vendor => vendor/js"
echo "You will also need to update the Gruntfile.js, see GRUNTFILE-CHANGES"
echo "JS files should be named *.dev.js during development, to be concatenated to something.js. Any development Sass-folders should be named *.dev."
echo "Files with .dev in the name will be deleted from the dist folder when building using yeoman-build"
echo "Update package.json with more information"


